import type { LeanSchema } from './types.js';

function normalizeType(t: string): string {
  if (t === 'any') return 'any';
  if (t === 'null') return 'null';
  return t;
}

function indent(level: number): string {
  return '  '.repeat(level);
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function toSafeIdentifier(s: string): string {
  return s.replace(/[^a-zA-Z0-9_$]/g, '_').replace(/^(\d)/, '_$1');
}

function generateTypeScriptType(schema: LeanSchema, name: string, level: number): string {
  const t = schema.type || 'any';
  let result = '';

  if (t === 'object' && schema.properties) {
    if (level === 0) {
      result += `export interface ${name} {\n`;
    } else {
      result += `{\n`;
    }
    const entries = Object.entries(schema.properties);
    for (const [key, prop] of entries) {
      const optional = schema.required && !schema.required.includes(key) ? '?' : '';
      const propType = typescriptTypeForSchema(prop, key, level + 1);
      result += `${indent(level + 1)}${toSafeIdentifier(key)}${optional}: ${propType};\n`;
    }
    result += `${indent(level)}}`;
    return result;
  }

  if (t === 'array' && schema.items) {
    const itemType = typescriptTypeForSchema(schema.items, 'Item', level);
    return `${itemType}[]`;
  }

  return normalizeType(t);
}

function typescriptTypeForSchema(schema: LeanSchema, name: string, level: number): string {
  const t = schema.type || 'any';

  if (schema.enum) {
    return schema.enum.map(v => JSON.stringify(v)).join(' | ');
  }

  if (t === 'object' && schema.properties) {
    return generateTypeScriptType(schema, name, level);
  }

  if (t === 'array' && schema.items) {
    const itemType = typescriptTypeForSchema(schema.items, name, level);
    return `${itemType}[]`;
  }

  return normalizeType(t);
}

export function generateTypeScript(schema: LeanSchema, name: string = 'Root'): string {
  let output = '';
  output += '// Auto-generated by LEAN schema codegen\n';
  output += '// Do not edit manually\n\n';
  output += generateTypeScriptType(schema, name, 0);
  output += '\n';
  return output;
}

function pythonTypeForSchema(schema: LeanSchema, level: number, definitions: Map<string, string>): string {
  const t = schema.type || 'any';

  if (schema.enum) {
    return `Literal[${schema.enum.map(v => JSON.stringify(v)).join(', ')}]`;
  }

  if (t === 'object' && schema.properties) {
    const className = `_Object${definitions.size}`;
    let lines: string[] = [];
    lines.push(`class ${className}(TypedDict):`);
    if (Object.keys(schema.properties).length === 0) {
      lines.push('    pass');
    } else {
      for (const [key, prop] of Object.entries(schema.properties)) {
        const propType = pythonTypeForSchema(prop, level + 1, definitions);
        const optional = schema.required && !schema.required.includes(key) ? 'NotRequired[' : '';
        const closeOpt = optional ? ']' : '';
        lines.push(`    ${toSafeIdentifier(key)}: ${optional}${propType}${closeOpt}`);
      }
    }
    definitions.set(className, lines.join('\n'));
    return className;
  }

  if (t === 'array' && schema.items) {
    const itemType = pythonTypeForSchema(schema.items, level, definitions);
    return `list[${itemType}]`;
  }

  const typeMap: Record<string, string> = {
    string: 'str',
    number: 'float',
    boolean: 'bool',
    null: 'None',
    any: 'Any',
  };
  return typeMap[t] || 'Any';
}

export function generatePython(schema: LeanSchema, name: string = 'Root'): string {
  const definitions = new Map<string, string>();
  const mainType = pythonTypeForSchema(schema, 0, definitions);

  let output = '';
  output += '# Auto-generated by LEAN schema codegen\n';
  output += '# Do not edit manually\n\n';
  output += 'from typing import TypedDict, NotRequired, Literal, Any\n\n';

  if (definitions.size > 0) {
    for (const [, body] of definitions) {
      output += body;
      output += '\n\n';
    }
  }

  if (definitions.has(mainType)) {
    output += `${name}: ${mainType}\n`;
  } else {
    output += `${name} = ${mainType}\n`;
  }

  return output;
}

function goTypeForSchema(schema: LeanSchema, level: number, definitions: Map<string, string>): string {
  const t = schema.type || 'any';

  if (schema.enum) {
    return 'string';
  }

  if (t === 'object' && schema.properties) {
    const structName = `_Struct${definitions.size}`;
    let lines: string[] = [];
    lines.push(`type ${structName} struct {`);
    for (const [key, prop] of Object.entries(schema.properties)) {
      const propType = goTypeForSchema(prop, level + 1, definitions);
      const jsonTag = `\`json:"${key}"\``;
      lines.push(`    ${capitalize(toSafeIdentifier(key))} ${propType} ${jsonTag}`);
    }
    lines.push('}');
    definitions.set(structName, lines.join('\n'));
    return structName;
  }

  if (t === 'array' && schema.items) {
    const itemType = goTypeForSchema(schema.items, level, definitions);
    return `[]${itemType}`;
  }

  const typeMap: Record<string, string> = {
    string: 'string',
    number: 'float64',
    boolean: 'bool',
    null: 'interface{}',
    any: 'interface{}',
  };
  return typeMap[t] || 'interface{}';
}

export function generateGo(schema: LeanSchema, name: string = 'Root'): string {
  const definitions = new Map<string, string>();
  const mainType = goTypeForSchema(schema, 0, definitions);

  let output = '';
  output += '// Auto-generated by LEAN schema codegen\n';
  output += '// Do not edit manually\n\n';
  output += 'package main\n\n';

  if (definitions.size > 0) {
    for (const [, body] of definitions) {
      output += body;
      output += '\n\n';
    }
  }

  const nameMap: Record<string, string> = {};
  let idx = 0;
  for (const [key] of definitions) {
    nameMap[key] = `_Struct${idx}`;
    idx++;
  }

  const finalName = nameMap[mainType] || mainType;
  output += `type ${capitalize(toSafeIdentifier(name))} = ${finalName}\n`;

  return output;
}
