export { parse, parseWasm } from './parser.js';
export { parse as parseData, parseSync } from './js-parser.js';
export { JsLeanParser } from './js-parser.js';
export { validate as validateSource } from './parser.js';
export { format as formatSource } from './parser.js';
export { format } from './serializer.js';
export { validate, validateStrict } from './validator.js';
export { SchemaValidator, validateSchema, generateSchema } from './schema.js';
export { query } from './query.js';
export { diff, formatDiff } from './diff.js';
export { ParseCache, cachedParse, defaultCache } from './cache.js';
export { ErrorCode, LeanParseError, LeanSerializeError } from './errors.js';
export { IncrementalParser, parseIncremental, defaultIncrementalParser } from './incremental.js';
export { LeanLexer } from './lexer.js';
export { generateTypeScript, generatePython, generateGo } from './codegen.js';
export { analyze, hasWarnings, formatWarnings } from './semantic.js';
export type { SemanticWarning, SemanticResult, } from './semantic.js';
export type { ASTNode, ASTNodeType, ParseResult, ParseError, ValidationResult, ValidationSeverity, Position, SourceLocation, Token, TokenValueType, ParseOptions, FormatOptions, LeanSchema, SchemaValidationError, SchemaValidationResult, QueryResult, DiffEntry, ValidationError, ValidationResponse, } from './types.js';
export { LEAN_VERSION, TokenType } from './types.js';
export declare function initParser(): Promise<void>;
export declare function isWasmAvailable(): boolean;
export declare function getWasmError(): Error | null;
//# sourceMappingURL=index.d.ts.map